project_id = "rflgjdpfisfuyowtrcil"

[functions.create-transaction]
verify_jwt = false

[functions.claim-reward]
verify_jwt = false

[functions.vault-deposit]
verify_jwt = false

[functions.vault-withdraw]
verify_jwt = false

[functions.vault-interest]
verify_jwt = false

[functions.upgrade-subscription]
verify_jwt = false
