import { useState } from 'react';
import { motion } from 'framer-motion';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Skeleton } from '@/components/ui/skeleton';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Target, Plus, Pencil, Trash2, Loader2, BarChart3, Rocket, Settings2 } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { api } from '@/lib/api-client';
import { toast } from 'sonner';
import { QueryError } from '@/components/ui/query-error';
import { useT } from '@/contexts/LanguageContext';

interface MissionTemplate {
  id: string;
  title: string;
  description: string;
  type: string;
  difficulty: string;
  reward_coins: number;
  reward_points: number;
  target_amount: number | null;
  age_group: string;
  is_active: boolean;
  conditions: Record<string, unknown>;
  created_at: string;
}

function useTemplates() {
  return useQuery({
    queryKey: ['mission-templates'],
    queryFn: async () => {
      const res = await api.get<any>('/mission-templates');
      const data = Array.isArray(res) ? res : (res?.data ?? []);
      return data as MissionTemplate[];
    },
  });
}

function useMissionAnalytics() {
  return useQuery({
    queryKey: ['mission-analytics'],
    queryFn: async () => {
      const res = await api.get<any>('/missions?fields=status,type,difficulty,is_auto_generated,source');
      const missions = Array.isArray(res) ? res : (res?.data ?? []);
      const total = missions.length;
      const completed = missions.filter((m: any) => m.status === 'completed').length;
      const autoGenerated = missions.filter((m: any) => m.is_auto_generated).length;
      const byType: Record<string, number> = {};
      const byDifficulty: Record<string, number> = {};
      missions.forEach((m: any) => {
        byType[m.type] = (byType[m.type] ?? 0) + 1;
        byDifficulty[m.difficulty ?? 'beginner'] = (byDifficulty[m.difficulty ?? 'beginner'] ?? 0) + 1;
      });
      return { total, completed, completionRate: total ? Math.round((completed / total) * 100) : 0, autoGenerated, byType, byDifficulty };
    },
  });
}

const TYPES = ['saving', 'budgeting', 'planning', 'learning', 'social', 'goal', 'daily', 'weekly'];
const DIFFICULTIES = ['beginner', 'explorer', 'saver', 'strategist', 'master'];
const AGE_GROUPS = ['all', '5-7', '8-12', '13-17'];

const difficultyColor: Record<string, string> = {
  beginner: 'bg-secondary/20 text-secondary',
  explorer: 'bg-primary/20 text-primary',
  saver: 'bg-accent/20 text-accent-foreground',
  strategist: 'bg-[hsl(var(--kivara-light-gold))] text-accent-foreground',
  master: 'bg-destructive/20 text-destructive',
};

export default function AdminMissions() {
  const t = useT();

  return (
    <div className="space-y-6 max-w-5xl mx-auto">
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
        <h1 className="text-2xl font-display font-bold">{t('admin.missions.title')}</h1>
        <p className="text-muted-foreground text-sm">{t('admin.missions.subtitle')}</p>
      </motion.div>

      <Tabs defaultValue="analytics">
        <TabsList className="bg-muted/50 rounded-2xl p-1">
          <TabsTrigger value="analytics" className="rounded-xl gap-1.5"><BarChart3 className="h-3.5 w-3.5" /> {t('admin.missions.tab.analytics')}</TabsTrigger>
          <TabsTrigger value="templates" className="rounded-xl gap-1.5"><Settings2 className="h-3.5 w-3.5" /> {t('admin.missions.tab.templates')}</TabsTrigger>
          <TabsTrigger value="engine" className="rounded-xl gap-1.5"><Rocket className="h-3.5 w-3.5" /> {t('admin.missions.tab.engine')}</TabsTrigger>
        </TabsList>

        <TabsContent value="analytics"><AnalyticsTab /></TabsContent>
        <TabsContent value="templates"><TemplatesTab /></TabsContent>
        <TabsContent value="engine"><EngineTab /></TabsContent>
      </Tabs>
    </div>
  );
}

function AnalyticsTab() {
  const t = useT();
  const { data, isLoading, error, refetch } = useMissionAnalytics();

  if (isLoading) return <div className="space-y-3">{Array.from({ length: 3 }).map((_, i) => <Skeleton key={i} className="h-24 rounded-2xl" />)}</div>;

  if (error) return <QueryError error={error} onRetry={() => refetch()} />;

  return (
    <div className="space-y-4 mt-4">
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        {[
          { label: t('admin.missions.stats.total'), value: data?.total ?? 0 },
          { label: t('admin.missions.stats.completed'), value: data?.completed ?? 0 },
          { label: t('admin.missions.stats.rate'), value: `${data?.completionRate ?? 0}%` },
          { label: t('admin.missions.stats.auto'), value: data?.autoGenerated ?? 0 },
        ].map(s => (
          <Card key={s.label} className="border-border/50">
            <CardContent className="p-4 text-center">
              <p className="text-2xl font-display font-bold">{s.value}</p>
              <p className="text-xs text-muted-foreground">{s.label}</p>
            </CardContent>
          </Card>
        ))}
      </div>

      <div className="grid md:grid-cols-2 gap-4">
        <Card className="border-border/50">
          <CardContent className="p-4">
            <h3 className="font-display font-bold text-sm mb-3">{t('admin.missions.by_type')}</h3>
            <div className="space-y-2">
              {Object.entries(data?.byType ?? {}).map(([type, count]) => (
                <div key={type} className="flex justify-between items-center">
                  <span className="text-sm capitalize">{type}</span>
                  <Badge variant="secondary" className="text-xs">{count as number}</Badge>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
        <Card className="border-border/50">
          <CardContent className="p-4">
            <h3 className="font-display font-bold text-sm mb-3">{t('admin.missions.by_difficulty')}</h3>
            <div className="space-y-2">
              {DIFFICULTIES.map(d => (
                <div key={d} className="flex justify-between items-center">
                  <Badge className={`text-xs ${difficultyColor[d]}`}>{d}</Badge>
                  <span className="text-sm font-display font-bold">{(data?.byDifficulty ?? {})[d] ?? 0}</span>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

function TemplatesTab() {
  const t = useT();
  const queryClient = useQueryClient();
  const { data: templates = [], isLoading } = useTemplates();
  const [open, setOpen] = useState(false);
  const [editTemplate, setEditTemplate] = useState<MissionTemplate | null>(null);
  const [form, setForm] = useState({ title: '', description: '', type: 'saving', difficulty: 'beginner', reward_coins: 10, reward_points: 10, target_amount: '', age_group: 'all' });

  const saveMutation = useMutation({
    mutationFn: async () => {
      const payload = {
        title: form.title,
        description: form.description,
        type: form.type,
        difficulty: form.difficulty,
        reward_coins: form.reward_coins,
        reward_points: form.reward_points,
        target_amount: form.target_amount ? parseInt(form.target_amount) : null,
        age_group: form.age_group,
      };
      if (editTemplate) {
        await api.patch('/mission-templates/' + editTemplate.id, payload as any);
      } else {
        await api.post('/mission-templates', payload as any);
      }
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['mission-templates'] });
      toast.success(editTemplate ? 'Template actualizado!' : 'Template criado!');
      setOpen(false);
      setEditTemplate(null);
      setForm({ title: '', description: '', type: 'saving', difficulty: 'beginner', reward_coins: 10, reward_points: 10, target_amount: '', age_group: 'all' });
    },
    onError: () => toast.error('Erro ao guardar template.'),
  });

  const deleteMutation = useMutation({
    mutationFn: async (id: string) => {
      await api.delete('/mission-templates/' + id);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['mission-templates'] });
      toast.success('Template eliminado!');
    },
  });

  const openEdit = (tpl: MissionTemplate) => {
    setEditTemplate(tpl);
    setForm({
      title: tpl.title,
      description: tpl.description,
      type: tpl.type,
      difficulty: tpl.difficulty,
      reward_coins: tpl.reward_coins,
      reward_points: tpl.reward_points,
      target_amount: tpl.target_amount?.toString() ?? '',
      age_group: tpl.age_group ?? 'all',
    });
    setOpen(true);
  };

  return (
    <div className="space-y-4 mt-4">
      <div className="flex justify-between items-center">
        <h3 className="font-display font-bold text-sm">{t('admin.missions.templates')}</h3>
        <Dialog open={open} onOpenChange={(v) => { setOpen(v); if (!v) setEditTemplate(null); }}>
          <DialogTrigger asChild>
            <Button size="sm" className="rounded-xl gap-1.5"><Plus className="h-3.5 w-3.5" /> {t('admin.missions.new_template')}</Button>
          </DialogTrigger>
          <DialogContent className="max-w-md">
            <DialogHeader>
              <DialogTitle className="font-display">{editTemplate ? t('admin.missions.edit_template') : t('admin.missions.new_template')}</DialogTitle>
            </DialogHeader>
            <div className="space-y-3">
              <Input placeholder={t('admin.missions.field.title')} value={form.title} onChange={e => setForm(f => ({ ...f, title: e.target.value }))} />
              <Input placeholder={t('admin.missions.field.description')} value={form.description} onChange={e => setForm(f => ({ ...f, description: e.target.value }))} />
              <div className="grid grid-cols-2 gap-3">
                <Select value={form.type} onValueChange={v => setForm(f => ({ ...f, type: v }))}>
                  <SelectTrigger><SelectValue /></SelectTrigger>
                  <SelectContent>{TYPES.map(t => <SelectItem key={t} value={t} className="capitalize">{t}</SelectItem>)}</SelectContent>
                </Select>
                <Select value={form.difficulty} onValueChange={v => setForm(f => ({ ...f, difficulty: v }))}>
                  <SelectTrigger><SelectValue /></SelectTrigger>
                  <SelectContent>{DIFFICULTIES.map(d => <SelectItem key={d} value={d} className="capitalize">{d}</SelectItem>)}</SelectContent>
                </Select>
              </div>
              <div className="grid grid-cols-3 gap-3">
                <Input type="number" placeholder="Coins" value={form.reward_coins} onChange={e => setForm(f => ({ ...f, reward_coins: parseInt(e.target.value) || 0 }))} />
                <Input type="number" placeholder="Points" value={form.reward_points} onChange={e => setForm(f => ({ ...f, reward_points: parseInt(e.target.value) || 0 }))} />
                <Input type="number" placeholder="Meta" value={form.target_amount} onChange={e => setForm(f => ({ ...f, target_amount: e.target.value }))} />
              </div>
              <Select value={form.age_group} onValueChange={v => setForm(f => ({ ...f, age_group: v }))}>
                <SelectTrigger><SelectValue /></SelectTrigger>
                <SelectContent>{AGE_GROUPS.map(a => <SelectItem key={a} value={a}>{a === 'all' ? 'Todas as idades' : `${a} anos`}</SelectItem>)}</SelectContent>
              </Select>
              <Button className="w-full rounded-xl" disabled={!form.title || saveMutation.isPending} onClick={() => saveMutation.mutate()}>
                {saveMutation.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : editTemplate ? t('common.save') : t('admin.missions.create')}
              </Button>
            </div>
          </DialogContent>
        </Dialog>
      </div>

      {isLoading ? (
        <div className="space-y-3">{Array.from({ length: 3 }).map((_, i) => <Skeleton key={i} className="h-16 rounded-2xl" />)}</div>
      ) : templates.length === 0 ? (
        <Card className="border-border/50"><CardContent className="py-8 text-center text-sm text-muted-foreground">{t('admin.missions.no_templates')}</CardContent></Card>
      ) : (
        <div className="space-y-2">
          {templates.map(tpl => (
            <Card key={tpl.id} className="border-border/50">
              <CardContent className="p-4 flex items-center gap-3">
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-0.5">
                    <h4 className="font-display font-bold text-sm">{tpl.title}</h4>
                    <Badge className={`text-xs ${difficultyColor[tpl.difficulty]}`}>{tpl.difficulty}</Badge>
                    <Badge variant="outline" className="text-xs capitalize">{tpl.type}</Badge>
                  </div>
                  <p className="text-xs text-muted-foreground truncate">{tpl.description}</p>
                  <div className="flex gap-2 mt-1 text-xs text-muted-foreground">
                    <span>🪙 {tpl.reward_coins}</span>
                    <span>⭐ {tpl.reward_points}</span>
                    <span>{tpl.age_group === 'all' ? 'Todas idades' : `${tpl.age_group} anos`}</span>
                  </div>
                </div>
                <div className="flex gap-1 shrink-0">
                  <Button size="icon" variant="ghost" className="h-8 w-8 rounded-xl" onClick={() => openEdit(tpl)}>
                    <Pencil className="h-3.5 w-3.5" />
                  </Button>
                  <Button size="icon" variant="ghost" className="h-8 w-8 rounded-xl text-destructive" onClick={() => deleteMutation.mutate(tpl.id)}>
                    <Trash2 className="h-3.5 w-3.5" />
                  </Button>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}

function EngineTab() {
  const t = useT();
  const [running, setRunning] = useState(false);

  const triggerGeneration = async (schedule: 'daily' | 'weekly') => {
    setRunning(true);
    try {
      const data = await api.post<{ generated?: number }>('/missions/generate', { schedule });
      toast.success(`${data?.generated ?? 0} missões geradas (${schedule})!`);
    } catch {
      toast.error('Erro ao gerar missões.');
    } finally {
      setRunning(false);
    }
  };

  return (
    <div className="space-y-4 mt-4">
      <Card className="border-border/50">
        <CardContent className="p-6">
          <div className="flex items-center gap-3 mb-4">
            <div className="w-12 h-12 rounded-2xl bg-primary/10 flex items-center justify-center">
              <Rocket className="h-6 w-6 text-primary" />
            </div>
            <div>
              <h3 className="font-display font-bold">{t('admin.missions.engine.title')}</h3>
              <p className="text-xs text-muted-foreground">{t('admin.missions.engine.subtitle')}</p>
            </div>
          </div>
          <p className="text-sm text-muted-foreground mb-4">{t('admin.missions.engine.description')}</p>
          <div className="flex gap-3">
            <Button className="rounded-xl gap-1.5 flex-1" disabled={running} onClick={() => triggerGeneration('daily')}>
              {running ? <Loader2 className="h-4 w-4 animate-spin" /> : <Target className="h-4 w-4" />}
              {t('admin.missions.engine.run_daily')}
            </Button>
            <Button variant="outline" className="rounded-xl gap-1.5 flex-1" disabled={running} onClick={() => triggerGeneration('weekly')}>
              {running ? <Loader2 className="h-4 w-4 animate-spin" /> : <Target className="h-4 w-4" />}
              {t('admin.missions.engine.run_weekly')}
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
